(() => {
  "use strict";

  const BUILD = "GD-AGENDA-WIZARD-V3-20260730";
  const qs = (s, r = document) => r.querySelector(s);
  const qsa = (s, r = document) => [...r.querySelectorAll(s)];
  const val = (s) => String(qs(s)?.value || "").trim();
  const chk = (s) => !!qs(s)?.checked;
  const esc = (v) => String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const emit = (el, type = "change") => el && el.dispatchEvent(new Event(type, { bubbles:true }));

  function style(){
    if (qs("#gdAgendaWizardV3Style")) return;
    const el = document.createElement("style");
    el.id = "gdAgendaWizardV3Style";
    el.textContent = `
      .gdAgendaWizardV3{width:min(1180px,calc(100vw - 22px))!important;padding:18px!important;border-radius:20px!important}
      .gdAgendaWizardV3 .swal2-title{margin:0 0 12px!important;font-size:24px!important}
      .gdAgendaWizardV3 .swal2-html-container{max-height:72vh!important;overflow:auto!important;margin:0!important;padding:0 3px 3px!important}
      .gdW3{display:grid;gap:14px;text-align:left}.gdW3Steps{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;position:sticky;top:0;z-index:20;padding:4px 0 11px;background:var(--surface,#0c1b2b)}
      .gdW3Step{border:1px solid var(--border,#22384f);background:var(--surface2,#102235);color:var(--muted,#a9bbd2);border-radius:13px;padding:10px 9px;display:flex;align-items:center;justify-content:center;gap:8px;font-weight:950;font-size:12px;text-align:center}
      .gdW3Step b{display:inline-flex;align-items:center;justify-content:center;width:23px;height:23px;border-radius:999px;border:1px solid currentColor}.gdW3Step.active{color:var(--text,#eaf2ff);border-color:rgba(25,195,125,.72);background:rgba(25,195,125,.14)}.gdW3Step.done{color:#19c37d;border-color:rgba(25,195,125,.42)}
      .gdW3Panel{display:none;gap:13px}.gdW3Panel.active{display:grid}.gdW3Hero{display:flex;justify-content:space-between;gap:14px;border:1px solid rgba(96,165,250,.28);background:rgba(96,165,250,.08);border-radius:16px;padding:13px 15px}.gdW3Hero strong{display:block;font-size:15px;margin-bottom:3px}.gdW3Hero span{display:block;color:var(--muted,#a9bbd2);font-size:12px;line-height:1.45}.gdW3Badge{padding:7px 10px;border-radius:999px;border:1px solid var(--border,#22384f);font-size:11px;font-weight:950;white-space:nowrap;height:max-content}
      .gdW3Modes{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.gdW3Mode{border:1px solid var(--border,#22384f);background:var(--surface2,#102235);color:var(--text,#eaf2ff);border-radius:15px;padding:14px;min-height:110px;display:grid;align-content:start;gap:6px;cursor:pointer;text-align:left}.gdW3Mode.active{border-color:rgba(25,195,125,.72);background:rgba(25,195,125,.12);box-shadow:0 0 0 3px rgba(25,195,125,.06)}.gdW3Mode i{font-style:normal;font-size:22px}.gdW3Mode strong{font-size:14px}.gdW3Mode small{color:var(--muted,#a9bbd2);font-size:11px;line-height:1.4}
      .gdW3Switches{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.gdW3Switch{border:1px solid var(--border,#22384f);border-radius:14px;background:rgba(0,0,0,.07);padding:12px 13px;display:flex;align-items:center;justify-content:space-between;gap:10px}.gdW3Switch strong{font-size:13px}.gdW3Switch small{display:block;color:var(--muted,#a9bbd2);font-size:11px;margin-top:2px}.gdW3Switch input{width:20px;height:20px}
      .gdW3Alert{display:none;border:1px solid rgba(245,158,11,.48);background:rgba(245,158,11,.10);border-radius:14px;padding:11px 13px;font-size:12px;line-height:1.5}.gdW3Alert.show{display:block}.gdW3LegacyMode{display:none!important}.gdW3Counts{display:grid!important;grid-template-columns:repeat(3,minmax(0,220px));gap:10px!important;border:1px solid var(--border,#22384f);border-radius:14px;padding:12px;background:rgba(0,0,0,.06)}.gdW3Counts>label:last-child{display:none!important}
      .gdW3Card{border:1px solid var(--border,#22384f)!important;background:rgba(0,0,0,.055)!important;border-radius:16px!important;padding:14px!important;display:grid!important;gap:12px!important}.gdW3Duration{display:flex;justify-content:space-between;gap:12px;border:1px solid rgba(25,195,125,.35);background:rgba(25,195,125,.08);border-radius:13px;padding:10px 12px;font-weight:950}.gdW3Duration.bad{border-color:rgba(239,68,68,.45);background:rgba(239,68,68,.09)}.gdW3Duration small{color:var(--muted,#a9bbd2);font-weight:800}.gdW3Sync{border:1px solid rgba(96,165,250,.28);background:rgba(96,165,250,.07);border-radius:12px;padding:9px 11px;font-size:11px;color:var(--muted,#a9bbd2)}
      .gdW3Mount{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;border:1px solid rgba(25,195,125,.34);background:rgba(25,195,125,.07);border-radius:14px;padding:11px 12px}.gdW3Mount small{display:block;color:var(--muted,#a9bbd2);font-size:11px;margin-top:3px}.gdW3Mount button{border:0;border-radius:10px;padding:9px 12px;background:#19c37d;color:#062016;font-weight:950;cursor:pointer}.gdAgendaWizardV3 #ag_day_montaje_wrap{border-color:rgba(25,195,125,.32)!important;background:rgba(25,195,125,.05)!important}
      .gdW3Review{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.gdW3Item{border:1px solid var(--border,#22384f);border-radius:12px;padding:9px 10px;background:rgba(0,0,0,.07);min-width:0}.gdW3Item small{display:block;color:var(--muted,#a9bbd2);font-weight:850;margin-bottom:3px}.gdW3Item div{font-weight:950;overflow-wrap:anywhere}.gdW3Item.wide{grid-column:span 3}.gdW3Hidden{display:none!important}.gdAgendaWizardV3 #ag_setup_toggle{display:none!important}
      .gdAgendaWizardV3 .swal2-actions{gap:9px!important;position:sticky;bottom:0;z-index:30;padding:12px 0 0!important;margin:8px 0 0!important;background:var(--surface,#0c1b2b)}.gdW3Back,.gdW3Next{border:1px solid var(--border,#22384f);border-radius:11px;padding:10px 16px;font-weight:950;cursor:pointer}.gdW3Back{background:transparent;color:var(--text,#eaf2ff)}.gdW3Next{background:#19c37d;color:#062016;border-color:transparent}.gdW3Footer{text-align:center;color:var(--muted,#a9bbd2);font-size:11px;font-weight:750}
      @media(max-width:820px){.gdW3Steps{grid-template-columns:repeat(2,minmax(0,1fr))}.gdW3Modes,.gdW3Switches,.gdW3Review{grid-template-columns:1fr}.gdW3Counts{grid-template-columns:1fr!important}.gdW3Item.wide{grid-column:span 1}.gdAgendaWizardV3{padding:13px!important}}
    `;
    document.head.appendChild(el);
  }

  function mins(t){const m=String(t||"").match(/^(\d{1,2}):(\d{2})$/);if(!m)return null;const h=+m[1],n=+m[2];return h>=0&&h<24&&n>=0&&n<60?h*60+n:null;}
  function duration(){const a=mins(val("#ag_hini")),b=mins(val("#ag_hfin"));if(a==null||b==null)return null;let d=b-a;if(d<=0)d+=1440;return {minutes:d,text:`${Math.floor(d/60)} h${d%60?` ${String(d%60).padStart(2,"0")} min`:""}`};}
  function alert(shell,items){const box=qs(".gdW3Alert",shell);items=(items||[]).filter(Boolean);box.classList.toggle("show",!!items.length);box.innerHTML=items.length?`<strong>Revisa esto:</strong><br>${items.map(x=>`• ${esc(x)}`).join("<br>")}`:"";}

  function syncTime(popup){
    const start=qs("#ag_hini",popup),end=qs("#ag_hfin",popup),tbd=qs("#ag_hrtbd",popup),box=qs("#gdW3Duration",popup),old=qs("#ag_duracion",popup);if(!start||!end||!tbd)return;
    const full=!!String(start.value||"").trim()&&!!String(end.value||"").trim();const before=tbd.checked;tbd.checked=!full;if(before!==tbd.checked)emit(tbd,"change");const d=duration();
    if(box){box.classList.toggle("bad",!d);box.innerHTML=d?`<div>Duración calculada: ${esc(d.text)}</div><small>${esc(start.value)} a ${esc(end.value)}</small>`:`<div>Horario pendiente</div><small>El evento quedará HR TBD</small>`;}
    if(old)old.textContent=d?`Duración: ${d.text}`:"Duración: —";
  }

  function preview(popup){const st=qs("#ag_calc_status",popup);if(st)st.textContent="Actualizando vista previa…";const n=qs("#ag_notes",popup);if(n)emit(n,"input");else emit(qs("#ag_quote",popup),"change");}
  async function waitPreview(popup){const t=Date.now();while(Date.now()-t<6500){const s=String(qs("#ag_calc_status",popup)?.textContent||"").trim();if(/^Listo$/i.test(s))return true;if(/error|faltan|no hay|inválid|inval/i.test(s))return false;await new Promise(r=>setTimeout(r,140));}return false;}

  function review(popup){
    const box=qs("#gdW3Review",popup);if(!box)return;const d=duration(),start=val("#ag_hini"),end=val("#ag_hfin"),addr=val("#ag_dir"),hr=chk("#ag_hrtbd")||!start||!end,dir=!addr,status=hr&&dir?"HR Y DIR TBD":hr?"HR TBD":dir?"DIR TBD":"Datos completos";
    const products=String(qs("#ag_products_day",popup)?.textContent||"").trim()||"Sin productos";const mount=String(qs("#ag_montaje_day",popup)?.value||"").trim()||String(qs("#ag_mont_manual",popup)?.value||"").trim()||"Sin montaje calculado";
    box.innerHTML=`<div class="gdW3Review"><div class="gdW3Item wide"><small>Cliente / evento</small><div>${esc(val("#ag_title")||"Evento confirmado")}</div></div><div class="gdW3Item"><small>Teléfono</small><div>${esc(val("#ag_tel")||"Por confirmar")}</div></div><div class="gdW3Item"><small>Comuna / lugar</small><div>${esc(val("#ag_loc")||"Por confirmar")}</div></div><div class="gdW3Item"><small>Dirección</small><div>${esc(addr||"DIR TBD")}</div></div><div class="gdW3Item"><small>Horario</small><div>${esc(hr?"HR TBD":`${start} – ${end}`)}</div></div><div class="gdW3Item"><small>Duración</small><div>${esc(d?d.text:"HR TBD")}</div></div><div class="gdW3Item"><small>Estado operativo</small><div>${esc(status)}</div></div><div class="gdW3Item"><small>Operadores</small><div>${esc(val("#ag_ops_day")||"1")}</div></div><div class="gdW3Item wide"><small>Productos</small><div style="white-space:pre-wrap">${esc(products)}</div></div><div class="gdW3Item wide"><small>Montaje</small><div style="white-space:pre-wrap">${esc(mount)}</div></div></div>`;
  }

  function validate(step,popup,shell){
    const e=[],mode=val("#ag_modality")||"simple";
    if(step===0){if(mode.includes("multiday")&&Number(val("#ag_days_n")||0)<2)e.push("Indica cuántos días tiene el evento (mínimo 2).");if(mode.includes("blocks")&&Number(val("#ag_blocks_n")||0)<1)e.push("Indica cuántos bloques tiene el evento.");if(chk("#ag_flag_multiloc")&&Number(val("#ag_locs_n")||0)<2)e.push("Indica cuántas locaciones tiene el evento (mínimo 2).");}
    if(step===1){syncTime(popup);if(val("#ag_hini")&&val("#ag_hfin")&&!duration())e.push("No se pudo calcular la duración.");if(!val("#ag_tel"))e.push("El teléfono quedará por confirmar.");if(!val("#ag_dir"))e.push("La dirección quedará DIR TBD.");}
    if(step===2){const distributed=mode!=="simple"||chk("#ag_flag_multiloc");if(distributed){const s=String(qs("#ag_alloc_status",popup)?.textContent||"").trim();if(s&&!/^OK:/i.test(s))e.push(s);}const s=String(qs("#ag_calc_status",popup)?.textContent||"").trim();if(/error|faltan|no hay|inválid|inval/i.test(s))e.push(s);if(!String(qs("#ag_products_day",popup)?.textContent||"").trim())e.push("No hay productos visibles.");if(!String(qs("#ag_montaje_day",popup)?.value||"").trim())e.push("Aún no se calculó el montaje sugerido.");if(Number(val("#ag_ops_day")||0)<1)e.push("Debe existir al menos 1 operador.");}
    alert(shell,e);return step===1?!e.some(x=>x.includes("duración")):!e.length;
  }

  function mode(popup,m){const s=qs("#ag_modality",popup);if(!s)return;s.value=m;emit(s,"change");qsa(".gdW3Mode",popup).forEach(b=>b.classList.toggle("active",b.dataset.mode===m));}
  function mountUI(popup){const h=qs("#ag_day_montaje_wrap > .muted",popup);if(h)h.textContent="Montaje y operadores sugeridos";const c=qs("#ag_montaje_confirm",popup);if(c)c.textContent="Aceptar sugerencia";const ed=qs("#ag_montaje_edit",popup);if(ed)ed.textContent="Agregar / editar montaje";const w=qs("#ag_day_montaje_wrap",popup);if(w&&!qs("#gdW3Mount",w)){const g=document.createElement("div");g.className="gdW3Mount";g.id="gdW3Mount";g.innerHTML=`<div><strong>Sugerencia calculada según los productos</strong><small>Puedes aceptarla o agregar carros, máquinas, mesas y operadores.</small></div><button type="button">Agregar al montaje</button>`;w.prepend(g);qs("button",g).onclick=()=>{ed?.click();const t=qs("#ag_montaje_day",popup);if(t){t.value=String(t.value||"").trim()+"\n";t.focus();t.setSelectionRange(t.value.length,t.value.length);}};}}

  function upgrade(popup){
    if(!popup||popup.dataset.gdAgendaWizardV3==="1")return;const html=qs(".swal2-html-container",popup),root=html?.firstElementChild,setup=qs("#ag_setup_body",popup),grid=qs(".agGrid",popup),left=grid?.children?.[0],right=grid?.children?.[1];if(!html||!root||!setup||!grid||!left||!right)return;
    const kids=[...setup.children],modeRow=kids[0],counts=kids[1],general=kids[2],priorBox=kids[3],allocator=kids[4];if(!modeRow||!counts||!general||!priorBox||!allocator)return;
    popup.dataset.gdAgendaWizardV3="1";popup.classList.remove("gdAgendaWizardV2");popup.classList.add("gdAgendaWizardV3");
    const shell=document.createElement("div");shell.className="gdW3";shell.innerHTML=`<div class="gdW3Steps"><div class="gdW3Step active" data-step="0"><b>1</b><span>Tipo de evento</span></div><div class="gdW3Step" data-step="1"><b>2</b><span>Datos principales</span></div><div class="gdW3Step" data-step="2"><b>3</b><span>Montaje y operación</span></div><div class="gdW3Step" data-step="3"><b>4</b><span>Revisión final</span></div></div><div class="gdW3Alert"></div><section class="gdW3Panel active" data-panel="0"><div class="gdW3Hero"><div><strong>Define cómo se realizará el evento</strong><span>Elige el formato principal y activa solamente los casos adicionales.</span></div><div class="gdW3Badge">Paso 1 de 4</div></div><div class="gdW3Modes"><button type="button" class="gdW3Mode active" data-mode="simple"><i>●</i><strong>Evento único</strong><small>Un día, un horario y una operación.</small></button><button type="button" class="gdW3Mode" data-mode="multiday"><i>▦</i><strong>Varios días</strong><small>Productos, horarios y operadores separados por día.</small></button><button type="button" class="gdW3Mode" data-mode="blocks"><i>▤</i><strong>Por bloques</strong><small>Productos, horarios y operadores separados por bloque.</small></button></div><div class="gdW3Switches"><label class="gdW3Switch"><span><strong>Montaje previo</strong><small>Crear bloque separado antes del evento.</small></span><input type="checkbox" id="gdW3Prior"></label><label class="gdW3Switch"><span><strong>Varias locaciones</strong><small>Usar direcciones diferentes.</small></span><input type="checkbox" id="gdW3Locs"></label></div></section><section class="gdW3Panel" data-panel="1"><div class="gdW3Hero"><div><strong>Datos principales</strong><span>La duración se calcula automáticamente al completar las horas.</span></div><div class="gdW3Badge">Paso 2 de 4</div></div><div class="gdW3Duration" id="gdW3Duration"></div><div class="gdW3Sync">Teléfono y dirección se guardarán también en la ficha del lead al confirmar.</div></section><section class="gdW3Panel" data-panel="2"><div class="gdW3Hero"><div><strong>Montaje, productos y operadores</strong><span>Cada cambio actualiza la vista previa antes de avanzar.</span></div><div class="gdW3Badge">Paso 3 de 4</div></div><div id="gdW3Calc" class="gdW3Card"></div><div id="gdW3Dist" class="gdW3Card"></div><div id="gdW3Ops" class="gdW3Card"></div></section><section class="gdW3Panel" data-panel="3"><div class="gdW3Hero"><div><strong>Revisión final</strong><span>Recién al confirmar se cambia el estado y se crea Calendar.</span></div><div class="gdW3Badge">Paso 4 de 4</div></div><div id="gdW3Review" class="gdW3Card"></div><div id="gdW3Calendar" class="gdW3Card"></div></section><div class="gdW3Footer">No cierre esta ventana durante la confirmación.</div>`;
    const panels=qsa(".gdW3Panel",shell);modeRow.classList.add("gdW3LegacyMode");counts.classList.add("gdW3Counts");panels[0].append(modeRow,counts);left.classList.add("gdW3Card");panels[1].append(left);
    const seg=qs("#ag_segments_wrap",left),blocks=qs("#ag_blocks_wrap",left),products=qs("#ag_products_wrap",left),day=qs("#ag_day_editor_wrap",right),status=qs("#ag_calc_status",right);if(status)qs("#gdW3Calc",shell).append(status);if(seg)qs("#gdW3Dist",shell).append(seg);if(blocks)qs("#gdW3Dist",shell).append(blocks);if(products)qs("#gdW3Dist",shell).append(products);qs("#gdW3Dist",shell).append(allocator);qs("#gdW3Ops",shell).append(day,general,priorBox);right.classList.add("gdW3Card");qs("#gdW3Calendar",shell).append(right);root.classList.add("gdW3Hidden");html.prepend(shell);const title=qs(".swal2-title",popup);if(title)title.textContent="Configurar agendamiento";mountUI(popup);
    const prior=qs("#gdW3Prior",popup),prior0=qs("#ag_flag_montaje_event",popup);if(prior&&prior0){prior.checked=prior0.checked;prior.onchange=()=>{prior0.checked=prior.checked;emit(prior0,"change");};}const loc=qs("#gdW3Locs",popup),loc0=qs("#ag_flag_multiloc",popup);if(loc&&loc0){loc.checked=loc0.checked;loc.onchange=()=>{loc0.checked=loc.checked;emit(loc0,"change");};}qsa(".gdW3Mode",popup).forEach(b=>b.onclick=()=>mode(popup,b.dataset.mode||"simple"));
    const time=()=>{syncTime(popup);preview(popup);};qs("#ag_hini",popup)?.addEventListener("change",time);qs("#ag_hfin",popup)?.addEventListener("change",time);qs("#ag_tel",popup)?.addEventListener("input",()=>preview(popup));qs("#ag_dir",popup)?.addEventListener("input",()=>preview(popup));qs("#ag_loc",popup)?.addEventListener("input",()=>preview(popup));
    const actions=qs(".swal2-actions",popup),confirm=qs(".swal2-confirm",popup),cancel=qs(".swal2-cancel",popup);if(!actions||!confirm||!cancel)return;const back=document.createElement("button"),next=document.createElement("button");back.type=next.type="button";back.className="gdW3Back";next.className="gdW3Next";back.textContent="Volver";next.textContent="Guardar y continuar";actions.insertBefore(back,confirm);actions.insertBefore(next,confirm);confirm.textContent="Confirmar agendamiento";cancel.textContent="Cancelar";let step=0;
    const show=async n=>{step=Math.max(0,Math.min(3,n));qsa(".gdW3Panel",shell).forEach((p,i)=>p.classList.toggle("active",i===step));qsa(".gdW3Step",shell).forEach((p,i)=>{p.classList.toggle("active",i===step);p.classList.toggle("done",i<step);});back.style.display=step?"inline-flex":"none";next.style.display=step===3?"none":"inline-flex";confirm.style.display=step===3?"inline-flex":"none";alert(shell,[]);syncTime(popup);if(step>=2){preview(popup);await waitPreview(popup);mountUI(popup);}if(step===3)review(popup);try{html.scrollTo({top:0,behavior:"smooth"});}catch(_){}};
    back.onclick=()=>show(step-1);next.onclick=async()=>{if(!validate(step,popup,shell))return;if(step<2){preview(popup);await waitPreview(popup);}await show(step+1);};qsa(".gdW3Step",shell).forEach(x=>x.onclick=()=>{const n=+x.dataset.step;if(n<=step)show(n);});confirm.addEventListener("click",e=>{if(!validate(2,popup,shell)){e.preventDefault();e.stopImmediatePropagation();show(2);return;}review(popup);confirm.textContent="Agendando…";},{capture:true});syncTime(popup);show(0);
  }

  function scan(){style();upgrade(qs(".swal2-popup.gdAgenda"));}
  const observer=new MutationObserver(()=>setTimeout(scan,0));if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{observer.observe(document.body,{childList:true,subtree:true});scan();});else{observer.observe(document.body,{childList:true,subtree:true});scan();}
  window.__GD_AGENDA_WIZARD_BUILD__=BUILD;
})();
