const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const money=new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const API_BASE=['localhost','127.0.0.1'].includes(String(location.hostname).toLowerCase())?'':'/crm';
const apiURL=p=>API_BASE?(String(p).startsWith('/crm/')?p:API_BASE+p):String(p).replace(/^\/crm/,'');
function authHeaders(extra={}){const gd=window.parent&&window.parent.GD;if(gd&&gd.authHeaders)return gd.authHeaders(extra);const token=localStorage.getItem('token')||localStorage.getItem('gd_token')||sessionStorage.getItem('token')||sessionStorage.getItem('gd_token')||'';return token?{...extra,Authorization:`Bearer ${token}`} : extra}
async function api(path,opts={}){const r=await fetch(apiURL(path),{...opts,headers:authHeaders(opts.headers||{})});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.detail?.message||b.detail||'Error de servidor');return b}
let connections=[];
async function loadConnections(){const b=await api('/api/finance/sii/connections');connections=b.items;$('#connectionGrid').innerHTML=connections.map(c=>`<article class="conn"><h3>${esc(c.name)}</h3><div class="metric">RUT</div><div class="value">${esc(c.rut_normalized)}</div><div class="metric">Estado</div><div class="value ${c.status==='CONNECTED'?'ok':''}">${esc(c.status||'DISCONNECTED')}</div><div class="metric">Certificado</div><div class="value">${esc(c.certificate_subject||'No configurado')}</div><div class="metric">Serie / válido hasta</div><div class="value">${esc(c.certificate_serial||'—')} • ${esc((c.certificate_valid_to||'—').slice(0,10))}</div><div class="toolbar"><button class="btn" onclick="testConnection(${c.id_legal_entity})">Probar conexión</button><label class="btn">Cambiar certificado<input hidden type="file" accept=".pfx,.p12" onchange="uploadCertificate(${c.id_legal_entity},this)"></label></div></article>`).join('')||'<div class="card">No hay entidades legales configuradas.</div>';const opts=connections.map(c=>`<option value="${c.id_legal_entity}">${esc(c.name)} • ${esc(c.rut_normalized)}</option>`).join('');$$('.entities').forEach(x=>x.innerHTML=opts)}
async function testConnection(id){try{await api(`/api/finance/sii/connections/${id}/test`,{method:'POST'});alert('Conexión SII certificada correctamente');loadConnections()}catch(e){alert(e.message)}}
async function uploadCertificate(id,input){const password=prompt('Password del certificado (no se almacenará en el navegador):');if(!password){input.value='';return}const fd=new FormData();fd.append('certificate',input.files[0]);fd.append('password',password);fd.append('environment','CERTIFICATION');try{await api(`/api/finance/sii/connections/${id}/certificate`,{method:'POST',body:fd});alert('Certificado protegido y configurado');loadConnections()}catch(e){alert(e.message)}finally{input.value=''}}
async function loadDocs(){const p=new URLSearchParams({page:'1',page_size:'100'});if($('#docQ').value)p.set('q',$('#docQ').value);if($('#dateFrom').value)p.set('date_from',$('#dateFrom').value);if($('#dateTo').value)p.set('date_to',$('#dateTo').value);if($('#docType').value)p.set('document_type',$('#docType').value);const b=await api('/api/finance/sii/received-documents?'+p);$('#docRows').innerHTML=b.items.map(d=>`<tr><td>${esc(d.issue_date)}</td><td>${esc(d.razon_social||d.supplier_name||d.issuer_name)}</td><td>${esc(d.rut_normalized)}</td><td>${esc(d.document_type)}</td><td>${esc(d.folio)}</td><td>${money.format(d.net_amount)}</td><td>${money.format(d.vat_amount)}</td><td>${money.format(d.exempt_amount)}</td><td>${money.format(d.total_amount)}</td><td>${esc(d.sii_status)}</td><td><span class="pill">${esc(d.financial_status)}</span></td><td>${esc(d.due_date||'—')}</td><td>${esc(d.source)}</td><td><button class="btn" onclick="showDocument(${d.id})">Ver</button></td></tr>`).join('')||'<tr><td colspan="14">Sin documentos</td></tr>'}
async function showDocument(id){const d=(await api(`/api/finance/sii/received-documents/${id}`)).item;$('#detailTitle').textContent=`DTE ${d.document_type} Nº ${d.folio}`;$('#detailBody').innerHTML=`<div class="grid"><div><b>Proveedor</b><p>${esc(d.razon_social||d.supplier_name)}<br>${esc(d.rut_normalized)}</p></div><div><b>Fechas</b><p>Emisión ${esc(d.issue_date)}<br>Vence ${esc(d.due_date||'—')}</p></div><div><b>Totales</b><p>Neto ${money.format(d.net_amount)}<br>IVA ${money.format(d.vat_amount)}<br>Total ${money.format(d.total_amount)}</p></div><div><b>Estados</b><p>SII ${esc(d.sii_status)}<br>Finanzas ${esc(d.financial_status)}<br>CxP ${esc(d.accounts_payable_id||'—')}</p></div></div><h4>Detalle</h4><div class="table"><table><thead><tr><th>Línea</th><th>Descripción</th><th>Cantidad</th><th>Unidad</th><th>Precio</th><th>Total</th></tr></thead><tbody>${d.lines.map(l=>`<tr><td>${l.line_number}</td><td>${esc(l.description)}</td><td>${esc(l.quantity)}</td><td>${esc(l.unit)}</td><td>${money.format(l.unit_price||0)}</td><td>${money.format(l.line_net_amount)}</td></tr>`).join('')}</tbody></table></div><p>SHA-256: <code>${esc(d.xml_sha256||'No disponible')}</code></p>${d.xml_storage_key?`<button class="btn" onclick="downloadXml(${id})">Descargar XML</button>`:''}`;$('#detailModal').classList.add('open')}
async function downloadXml(id){const r=await fetch(apiURL(`/api/finance/sii/received-documents/${id}/xml?download=true`),{headers:authHeaders()});if(!r.ok)throw new Error('No fue posible descargar el XML');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`DTE-${id}.xml`;a.click();URL.revokeObjectURL(url)}
async function loadSuppliers(){const p=new URLSearchParams({page:'1',page_size:'100'});if($('#supplierQ').value)p.set('q',$('#supplierQ').value);const b=await api('/api/finance/sii/suppliers?'+p);$('#supplierRows').innerHTML=b.items.map(s=>`<tr><td>${esc(s.razon_social||s.nombre)}</td><td>${esc(s.rut_normalized)}</td><td>${esc(s.giro||'—')}</td><td>${esc(s.comuna_tributaria||'—')}</td><td>${esc(s.source||'—')} ${s.last_sii_update_at?'<span class="pill ok">SII</span>':''}</td><td>${esc(s.primera_factura||'—')}</td><td>${esc(s.ultima_factura||'—')}</td><td>${s.cantidad_documentos}</td><td>${money.format(s.total_comprado)}</td><td>${money.format(s.saldo_pendiente)}</td></tr>`).join('')||'<tr><td colspan="10">Sin proveedores tributarios</td></tr>'}
async function loadRuns(){const b=await api('/api/finance/sii/sync-runs');$('#runRows').innerHTML=b.items.map(r=>`<tr><td>${esc(r.started_at)}</td><td>${esc(r.source)}</td><td>${esc(r.status)}</td><td>${r.records_seen}</td><td>${r.records_inserted}</td><td>${r.records_updated}</td><td>${r.records_failed}</td><td>${r.suppliers_created}</td><td>${r.payables_created}</td></tr>`).join('')||'<tr><td colspan="9">Sin sincronizaciones</td></tr>'}
async function submitImport(form,path){const out=$('#importResult');out.textContent='Procesando…';try{out.textContent=JSON.stringify(await api(path,{method:'POST',body:new FormData(form)}),null,2);await Promise.all([loadDocs(),loadSuppliers(),loadRuns()])}catch(e){out.textContent=e.message}}
async function importEmail(){const out=$('#importResult');out.textContent='Consultando Correo GIA en modo lectura…';try{out.textContent=JSON.stringify(await api('/api/finance/sii/import/email',{method:'POST'}),null,2);await Promise.all([loadDocs(),loadSuppliers(),loadRuns()])}catch(e){out.textContent=e.message}}
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===t));$$('.pane').forEach(x=>x.classList.toggle('active',x.id===t.dataset.pane))});
$('#filterDocs').onclick=loadDocs;$('#filterSuppliers').onclick=loadSuppliers;$('#reload').onclick=()=>Promise.all([loadConnections(),loadDocs(),loadSuppliers(),loadRuns()]);$('#xmlForm').onsubmit=e=>{e.preventDefault();submitImport(e.target,'/api/finance/sii/import/xml')};$('#rcvForm').onsubmit=e=>{e.preventDefault();submitImport(e.target,'/api/finance/sii/import/rcv')};$('#emailImport').onclick=importEmail;
window.testConnection=testConnection;window.uploadCertificate=uploadCertificate;window.showDocument=showDocument;window.downloadXml=downloadXml;
Promise.all([loadConnections(),loadDocs(),loadSuppliers(),loadRuns()]).catch(e=>alert(e.message));
