"""init users

Revision ID: 943262876cf3
Revises: 
Create Date: 2025-10-27 17:25:09.939778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '943262876cf3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_table('usuario_marcas')
    op.drop_table('comunas')
    op.drop_index(op.f('ix_cotizaciones_id_cotizacion'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_cotizacion_productos_id'), table_name='cotizacion_productos')
    op.drop_table('cotizacion_productos')
    op.drop_table('productos')
    op.drop_table('marcas')
    op.drop_table('usuarios')
    op.drop_index(op.f('idx_leads_comuna'), table_name='leads')
    op.drop_index(op.f('idx_leads_estado'), table_name='leads')
    op.drop_index(op.f('idx_leads_marca'), table_name='leads')
    op.drop_index(op.f('idx_leads_usuario'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('categorias')
    op.drop_table('tipo_cliente')
    op.drop_table('estados')
    op.drop_table('segmentacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentacion',
    sa.Column('id_segmentacion', sa.INTEGER(), server_default=sa.text("nextval('segmentacion_id_segmentacion_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_segmentacion', name='segmentacion_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('estados',
    sa.Column('id_estado', sa.INTEGER(), server_default=sa.text("nextval('estados_id_estado_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_estado', name='estados_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tipo_cliente',
    sa.Column('id_tipo_cliente', sa.INTEGER(), server_default=sa.text("nextval('tipo_cliente_id_tipo_cliente_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_cliente', name='tipo_cliente_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('categorias',
    sa.Column('id_categoria', sa.INTEGER(), server_default=sa.text("nextval('categorias_id_categoria_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_categoria', name='categorias_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('leads',
    sa.Column('id_lead', sa.INTEGER(), server_default=sa.text("nextval('leads_id_lead_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('codigo_cliente', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_ingreso', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id_marca', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_cliente', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_tipo_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plataforma', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_evento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dia', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mes', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('semana', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_comuna', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('whatsapp_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('monto_cotizado', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('id_estado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_cierre', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('seguimiento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero_cotizacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id_segmentacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fecha_seguimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('segmentacion', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], name='leads_id_categoria_fkey'),
    sa.ForeignKeyConstraint(['id_comuna'], ['comunas.id_comuna'], name='leads_id_comuna_fkey'),
    sa.ForeignKeyConstraint(['id_estado'], ['estados.id_estado'], name='leads_id_estado_fkey'),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='leads_id_marca_fkey'),
    sa.ForeignKeyConstraint(['id_segmentacion'], ['segmentacion.id_segmentacion'], name='leads_id_segmentacion_fkey'),
    sa.ForeignKeyConstraint(['id_tipo_cliente'], ['tipo_cliente.id_tipo_cliente'], name='leads_id_tipo_cliente_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='leads_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_lead', name='leads_pkey'),
    sa.UniqueConstraint('codigo_cliente', name='leads_codigo_cliente_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_leads_usuario'), 'leads', ['id_usuario'], unique=False)
    op.create_index(op.f('idx_leads_marca'), 'leads', ['id_marca'], unique=False)
    op.create_index(op.f('idx_leads_estado'), 'leads', ['id_estado'], unique=False)
    op.create_index(op.f('idx_leads_comuna'), 'leads', ['id_comuna'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.INTEGER(), server_default=sa.text("nextval('usuarios_id_usuario_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('id_marca', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='usuarios_id_marca_fkey'),
    sa.PrimaryKeyConstraint('id_usuario', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('marcas',
    sa.Column('id_marca', sa.INTEGER(), server_default=sa.text("nextval('marcas_id_marca_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_marca', name='marcas_pkey'),
    sa.UniqueConstraint('nombre', name='marcas_nombre_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.INTEGER(), server_default=sa.text("nextval('productos_id_producto_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_marca', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_producto', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('costo', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('precio_sugerido', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('creado_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='productos_id_marca_fkey'),
    sa.PrimaryKeyConstraint('id_producto', name='productos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cotizacion_productos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cotizacion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], name=op.f('cotizacion_productos_id_cotizacion_fkey')),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name=op.f('cotizacion_productos_id_producto_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cotizacion_productos_pkey'))
    )
    op.create_index(op.f('ix_cotizacion_productos_id'), 'cotizacion_productos', ['id'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('id_cotizacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_lead', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('pdf_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_lead'], ['leads.id_lead'], name=op.f('cotizaciones_id_lead_fkey')),
    sa.PrimaryKeyConstraint('id_cotizacion', name=op.f('cotizaciones_pkey'))
    )
    op.create_index(op.f('ix_cotizaciones_id_cotizacion'), 'cotizaciones', ['id_cotizacion'], unique=False)
    op.create_table('comunas',
    sa.Column('id_comuna', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('costo_despacho', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_comuna', name=op.f('comunas_pkey')),
    sa.UniqueConstraint('nombre', name=op.f('comunas_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('usuario_marcas',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_marca', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name=op.f('usuario_marcas_id_marca_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('usuario_marcas_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id_usuario', 'id_marca', name=op.f('usuario_marcas_pkey'))
    )
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
