import os
import re
from datetime import datetime, timezone

import psycopg


def mask_dsn(dsn: str) -> str:
    return re.sub(r"(postgresql://)([^:]+):([^@]+)@", r"\1\2:****@", dsn)


def exec_sql(conn, title: str, sql: str):
    print(f"\n--- {title} ---")
    with conn.cursor() as cur:
        cur.execute(sql)
    conn.commit()
    print("OK")


def main():
    dsn = os.getenv("DATABASE_URL")
    if not dsn:
        raise RuntimeError('DATABASE_URL no está seteada. Ej: export DATABASE_URL="postgresql://BDGD:***@localhost:5432/BDGD"')

    print(f"Conectando a: {mask_dsn(dsn)}")
    cn = psycopg.connect(dsn)

    with cn.cursor() as cur:
        cur.execute("SELECT current_database(), current_user, now()")
        db, usr, now = cur.fetchone()
    print(f"DB={db} USER={usr} NOW={now}")

    # 1) Tabla estados de lead
    exec_sql(
        cn,
        "Tabla lead_estados (create if missing)",
        """
        CREATE TABLE IF NOT EXISTS public.lead_estados(
          id_estado integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          estado text NOT NULL,
          color text DEFAULT '#64748b',
          orden integer DEFAULT 0,
          is_active boolean DEFAULT true
        );
        """
    )

    exec_sql(
        cn,
        "lead_estados: constraints",
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname='lead_estados_estado_key'
          ) THEN
            ALTER TABLE public.lead_estados
              ADD CONSTRAINT lead_estados_estado_key UNIQUE (estado);
          END IF;
        END $$;
        """
    )

    # Seed de estados (con IDs fijos para que calce con leads existentes)
    exec_sql(
        cn,
        "lead_estados: seed baseline",
        """
        INSERT INTO public.lead_estados (id_estado, estado, color, orden, is_active)
        VALUES
          (1, 'NUEVO',        '#06b6d4', 10, true),
          (2, 'CONTACTADO',   '#3b82f6', 20, true),
          (3, 'COTIZADO',     '#f59e0b', 30, true),
          (4, 'EN NEGOCIACION','#a855f7',40, true),
          (5, 'GANADO',       '#22c55e', 50, true),
          (6, 'DECLINADO',    '#ef4444', 60, true)
        ON CONFLICT (id_estado) DO UPDATE SET
          estado=EXCLUDED.estado,
          color=EXCLUDED.color,
          orden=EXCLUDED.orden,
          is_active=EXCLUDED.is_active;
        """
    )

    # 2) Tabla comunas (si no existe)
    exec_sql(
        cn,
        "Tabla comunas (create if missing)",
        """
        CREATE TABLE IF NOT EXISTS public.comunas(
          id_comuna integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          comuna text NOT NULL,
          is_active boolean DEFAULT true
        );
        """
    )

    exec_sql(
        cn,
        "comunas: constraints",
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname='comunas_comuna_key'
          ) THEN
            ALTER TABLE public.comunas
              ADD CONSTRAINT comunas_comuna_key UNIQUE (comuna);
          END IF;
        END $$;
        """
    )

    # Seed “inteligente” desde leads: crea comunas placeholder si tu maestro real no está cargado
    exec_sql(
        cn,
        "comunas: seed desde leads (placeholder)",
        """
        INSERT INTO public.comunas (id_comuna, comuna, is_active)
        SELECT DISTINCT
          l.id_comuna,
          ('Comuna ' || l.id_comuna::text) AS comuna,
          true
        FROM public.leads l
        WHERE l.id_comuna IS NOT NULL AND l.id_comuna > 0
        ON CONFLICT (id_comuna) DO NOTHING;
        """
    )

    # 3) Auditoría rápida
    with cn.cursor() as cur:
        cur.execute("SELECT count(*) FROM public.lead_estados")
        est = cur.fetchone()[0]
        cur.execute("SELECT count(*) FROM public.comunas")
        com = cur.fetchone()[0]
    print(f"\n✅ Migración v4 aplicada. lead_estados={est} comunas={com}")

    cn.close()


if __name__ == "__main__":
    main()
