[Interface]
PrivateKey = eD6P/VfOtSNfW6lA47jTNgSWSz3zXk666uB/wAF3zFA=
Address = 10.77.0.13/32

[Peer]
PublicKey = ccDo/yg7kQp5C6Pjn3gR5b8Ns0OmUz+8l8AMz6M8DQI=
Endpoint = 181.43.135.236:51820
AllowedIPs = 10.77.0.1/32
PersistentKeepalive = 25
